project:
  type: website

website:
  title: "samantha-manuel.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Final Projects
        menu:
          - href: EPPS6356_Final.pdf
            text: EPPS6356 Final
          - href: EPPS6302_Final.pdf
            text: EPPS6302 Final
          - href: POV_Code.pdf
            text: Final Project Code
          - href: "https://haleypuddy.github.io/pov_dash2.html"
            text: Final Project Storyboard
      - href: cv.pdf
        text: CV
      - href: "https://samantha-manuel.github.io/samantha-manuel.github.io-blog/"
        text: Blog
      - text: Critiques/Reviews
        menu:
          - edwardtufte.qmd
          - googleflu_wickham.qmd
          - comparison.qmd
          - Malinowski.qmd
      - text: Assignments
        menu:
          - assign01.qmd
          - assign02.qmd
          - assign03.qmd
          - assign04.qmd
          - assign05.qmd
          - assign06.qmd
          - assign07.qmd
          - assign09.qmd
          - assign10.qmd
          - assign02_6302.qmd
          - assign03_6302.qmd
          - assign04_6302.qmd
          - assign05_6302.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

